# Generated by Django 4.2.6 on 2023-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='media/Dish_image'),
        ),
    ]
