# Generated by Django 4.2.6 on 2023-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dish_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
