# Generated by Django 4.2.6 on 2023-10-16 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0003_alter_dish_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
