# Generated by Django 4.2.6 on 2023-10-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
    ]
